### ISSUE TITLE
Command matrix deploy app not working properly.

### ISSUE THREAD

**Issue by caike** [matrix-io/matrix-cli#117]
The error message says:

> Unable to reach device, the application will be installed as soon as your device is available

I have connected the Matrix Voice to a raspberry pi and am writing a node test app following the tutorial on https://matrix-io.github.io/matrix-documentation/matrix-os/overview/cli/

What I have done:

1. Registered my account with `matrix register`
2. Confirmed by account and looking at the empty dashboard.
3. Registered my device with `matrix register device`.
4. I see the device listed on `matrix list devices`.

Couple facts:

1. The device is NOT listed on my web dashboard.
2. The command `matrix list decices` is showing my device.
3. The command `matrix list devices` is showing "ok: no" and "Last Online: 48 years ago."
4. The lights on my Matrix voice are all on/green, so it is connected.

Any insights ?

**Comment by Hermitter** [comment]
Do you have [MOS](https://matrix-io.github.io/matrix-documentation/matrix-os/getting-started/installation/) installed?

**Comment by caike** [comment]
That was it. Thank you! 👍
