### ISSUE TITLE
missing links in documentation

### ISSUE THREAD

**Issue by amoun00** [matrix-io/matrix-cli#20]
Hello guys,

the links in the documentation don't work. 

- registering an admobilize account is not available
- setup a simulator link doesn't work
- documentation unclear and confusing

Please some help

**Comment by eighteyes** [comment]
Hi Rabih,

Thanks for writing.

We're wrapping up the cli tool and the servers. Within a day or two you should be able to register for an account, and run MatrixOS applications. 

Can you point me to the broken link, and to where you are looking at documentation?

Thanks,
Sean
