### ISSUE TITLE
Token Error on Login

### ISSUE THREAD

**Issue by eighteyes** [matrix-io/matrix-cli#24]
```
Authentication error (auth/custom-token-mismatch):  The custom token corresponds to a different audience.
```

Temporary Fix:

Set environment
`matrix set env dev`

**Comment by eighteyes** [comment]
Error. That should be `matrix set env rc`

**Comment by brianofrokk3r** [comment]
@eighteyes @diegoribero happening anymore?

**Comment by eighteyes** [comment]
![screen shot 2016-10-17 at 12 06 15 pm](https://cloud.githubusercontent.com/assets/405274/19452475/05354bba-9466-11e6-881b-4b448bf019a0.png)
Clue

**Comment by brianofrokk3r** [comment]
@eighteyes is this happening anymore?

**Comment by eighteyes** [comment]
I saw it recently, so yes.
