### ISSUE TITLE
Register device not finishing

### ISSUE THREAD

**Issue by diegoribero** [matrix-io/matrix-cli#27]
When registering a new device, the message `Device registered succesfully` is displayed, however the **id** and **secret** are never shown.

**Comment by amoun00** [comment]
same here

**Comment by diegoribero** [comment]
Issue identified, a fix is on its way :)

**Comment by amoun00** [comment]
actually device id is showing for me but not the secret.

**Comment by eighteyes** [comment]
run the command with `DEBUG=*` maybe it's in the payloads somewhere :(

**Comment by diegoribero** [comment]
Fix is here, packaged in the form of **v1.1.20**, please update and enjoy
