### ISSUE TITLE
Install doesn't find device

### ISSUE THREAD

**Issue by gordinh** [matrix-io/matrix-cli#48]
So, i'am trying to install an app from the store, but i receive `unable to reach` like i show below. The weird is on my OS it says is installed, but on my CLI it's unable to reach. This has happened with two apps from the store that i tried to install, but my apps that i build, install just fine.

```
____ | Installing  vehicle  ==>  df0ebc72dfe0
 ==== ^^^^ GRANT ACCESS ???? ^^^^ ====
{ sensors: [ 'camera' ], services: [ 'vehicle-detection' ] }
? OK to allow vehicle access to the above? Yes

⇒ Installing vehicle with policy:

 sensors:
 ✅  0

 services:
 ✅  0
 Installation progress:
Awaiting installation on Device...
 Unable to reach device, the application will be installed as soon as your device is available
```

**Comment by eighteyes** [comment]
thanks @gordinh this is a known issue, we're working at it.

**Comment by eighteyes** [comment]
@gordinh please try again, make sure to use the right environment.

**Comment by brianofrokk3r** [comment]
@eighteyes resolved?

**Comment by gordinh** [comment]
@eighteyes i updated the cli so maybe it was this. it's working now, thx
