### ISSUE TITLE
TypeError: Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by daadu** [matrix-io/matrix-cli#52]
```
$ matrix register device
/usr/lib/node_modules/matrix-cli/bin/matrix-validate.js:23
  var token = Matrix.config.user.token;
                                ^

TypeError: Cannot read property 'token' of undefined
    at token (/usr/lib/node_modules/matrix-cli/bin/matrix-validate.js:23:33)
    at Object.user (/usr/lib/node_modules/matrix-cli/bin/matrix-validate.js:3:3)
    at /usr/lib/node_modules/matrix-cli/bin/matrix-register.js:14:23
    at /usr/lib/node_modules/matrix-cli/node_modules/node-yaml-localize/lib/node-yaml-localize/translator.js:175:24
    at next (/usr/lib/node_modules/matrix-cli/node_modules/node-yaml-localize/lib/node-yaml-localize/translator.js:228:35)
    at /usr/lib/node_modules/matrix-cli/node_modules/node-yaml-localize/lib/node-yaml-localize/translator.js:240:25
    at FSReqWrap.oncomplete (fs.js:123:15)

```

**Comment by brianofrokk3r** [comment]
Hey @daadu,

Thanks for this message, can you please type `matrix` in your terminal, and check what version you are using? We're up to `1.2.6`. If you need to upgrade, just run `npm install matrix-cli -g`.

**Comment by daadu** [comment]
yes it is 1.2.6

**Comment by daadu** [comment]
node version is : v6.9.1

**Comment by brianofrokk3r** [comment]
Hey @daadu,

Thanks for that, so far unable to reproduce with node version `6.9.1`. I ran through the following process:
```
sudo npm install -g matrix-cli
matrix set env rc
matrix login
matrix register device
```

Try:
```
// uninstall current version
sudo npm uninstall -g matrix-cli

// reinstall latest version
sudo npm install -g matrix-cli
```

Questions:
* What OS and version are you running?

**Comment by daadu** [comment]
Ohh this worked... reinstalling 

I don't know what went wrong. :)

Thank You.

**Comment by brianofrokk3r** [comment]
@daadu no problem. Glad it worked!

**Comment by ScottChapman** [comment]
I am experiencing same problem. literally just installed cli on my mac. Registered OK, but getting same error as above...

**Comment by eighteyes** [comment]
@ScottChapman hi, are you running the `login` command? you don't get logged in when you register. that's what sets the token. we can catch that error.
